#ifndef DIO_config_H_
#define DIO_config_H_

#define DIO_u8INPUT 0
#define DIO_u8OUTPUT 1
 

#define DIO_u8_PIN_DIR0 DIO_u8INPUT
#define DIO_u8_PIN_DIR1 DIO_u8INPUT
#define DIO_u8_PIN_DIR2 DIO_u8INPUT
#define DIO_u8_PIN_DIR3 DIO_u8INPUT
#define DIO_u8_PIN_DIR4 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR5 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR6 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR7 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR8 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR9 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR10 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR11 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR12 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR13 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR14 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR15 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR16 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR17 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR18 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR19 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR20 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR21 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR22 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR23 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR24 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR25 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR26 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR27 DIO_u8OUTPUT

#define DIO_u8_PIN_DIR28 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR29 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR30 DIO_u8OUTPUT
#define DIO_u8_PIN_DIR31 DIO_u8OUTPUT
                         
#endif                
